repos:
  # black
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ["--line-length", "120"]

  # isort
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
